# Generated by Django 2.2.7 on 2019-11-19 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0019_django_2_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrtemplate',
            name='up_id',
        ),
        migrations.AlterField(
            model_name='buildtemplate',
            name='wrtemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.WRTemplate'),
        ),
    ]
